services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-frontend
    ports:
      - "8112:8112"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8111
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev