version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: product-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: product-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASS: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${PORT}:8111"

volumes:
  pgdata: